//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Repuetos_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_COMPRAS
    {
        public int EC_COMPRAS_ID { get; set; }
        public int EC_COMPRAS_USUARIOS { get; set; }
        public System.DateTime EC_COMPRAS_FECHA { get; set; }
        public int EC_COMPRAS_CANTIDAD { get; set; }
        public int EC_COMPRAS_PRODUCTOS { get; set; }
        public double EC_COMPRAS_IMPUESTO { get; set; }
        public Nullable<double> EC_COMPRAS_SUBTOTAL { get; set; }
        public int EC_COMPRAS_TOTAL { get; set; }
        public string EC_COMPRAS_PAGO { get; set; }
    
        public virtual EC_PRODUCTOS EC_PRODUCTOS { get; set; }
        public virtual EC_USUARIOS EC_USUARIOS { get; set; }
    }
}
