//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Repuetos_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EC_PRODUCTOS()
        {
            this.EC_COMPRAS = new HashSet<EC_COMPRAS>();
        }
    
        public int EC_PRODUCTO_ID { get; set; }
        public string EC_PRODUCTO_NOMBRE { get; set; }
        public string EC_PRODUCTO_MARCA { get; set; }
        public string EC_PRODUCTO_URL_IMAGEN { get; set; }
        public string EC_PRODUCTO_DESCRIPCION { get; set; }
        public double EC_PRODUCTO_PRECIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EC_COMPRAS> EC_COMPRAS { get; set; }
    }
}
