//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Repuetos_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PROYECTO_WEBEntities : DbContext
    {
        public DB_PROYECTO_WEBEntities()
            : base("name=DB_PROYECTO_WEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EC_COMPRAS> EC_COMPRAS { get; set; }
        public virtual DbSet<EC_PRODUCTOS> EC_PRODUCTOS { get; set; }
        public virtual DbSet<EC_USUARIOS> EC_USUARIOS { get; set; }
    }
}
