//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Repuetos_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EC_USUARIOS()
        {
            this.EC_COMPRAS = new HashSet<EC_COMPRAS>();
        }
    
        public int EC_USUARIOS_ID { get; set; }
        public string EC_USUARIOS_CEDULA { get; set; }
        public string EC_USUARIOS_NOMBRE { get; set; }
        public string EC_USUARIOS_APE1 { get; set; }
        public string EC_USUARIOS_APE2 { get; set; }
        public string EC_USUARIOS_TELEFONO { get; set; }
        public string EC_USUARIOS_EMAIL { get; set; }
        public string EC_USUARIOS_ESTADO { get; set; }
        public string EC_USUARIOS_CONTRASENNA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EC_COMPRAS> EC_COMPRAS { get; set; }
    }
}
